### ISSUE TITLE
Parsing Blocks and SimpleBlocks?

### ISSUE THREAD

**Issue by RationalCoding** [themasch/node-ebml#22]
Does this module have support for parsing Matroska blocks?

Currently the output is lacking any track numbers, timecodes, or anything else contained within the block. I assume this is within the "data" UIntArray in the "SimpleBlock" objects?

Is there any option to parse these blocks, or is that outside the scope of this project?

**Comment by themasch** [comment]
@RationalCoding  I know I'm late (but only about 12 months!), but if this is still interesting for you, could you check if the new additions in master fix your issue? It will be released as 3.0 soon (I hope…)

**Comment by RationalCoding** [comment]
Timestamps and track numbers are exactly what I needed! Thanks.

**Comment by themasch** [comment]
Nice, i'll let you know when 3.0 hits npm
