### ISSUE TITLE
Support for newest Matroska elements

### ISSUE THREAD

**Issue by dvdeurse** [themasch/node-ebml#4]
The schema currently does not support the new elements CueRelativePosition (F0) and CueDuration (B2). When parsing files containing these new elements, the parser fails because the getSchemaInfo function returns an undefined value.

**Comment by maxogden** [comment]
https://github.com/themasch/node-ebml/pull/9 fixes this

**Comment by themasch** [comment]
this should be fixed by version 0.2.0 now. correct? If not, reopen please
